### ISSUE TITLE
Invalid JSON input causes HTTP error 500

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Question-Answering#10]
Any invalid JSON input causes a 500 HTTP code, e.g.
```
{
}
```

or 

```
{
  "paragraphs": [
  ]
}
```

**Comment by kmh4321** [comment]
```
{
  "paragraphs": [
  ]
}
``` 
returns a `200`. I agree with the other one, will fix that. 
![image](https://user-images.githubusercontent.com/32885872/64901480-9cebc100-d64e-11e9-9c6f-dbc6fcfd05e6.png)

**Comment by kmh4321** [comment]
I agree with the other one - `{}` returns a `500` when it really should return `400`.
