### ISSUE TITLE
Deployment on Red Hat OpenShift fails

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Question-Answering#14]
During startup the following error is logged:

```
Traceback (most recent call last):
  File "app.py", line 18, in <module>
    from api import ModelMetadataAPI, ModelPredictAPI
  File "/workspace/api/__init__.py", line 18, in <module>
    from .predict import ModelPredictAPI  # noqa
  File "/workspace/api/predict.py", line 64, in <module>
    class ModelPredictAPI(PredictAPI):
  File "/workspace/api/predict.py", line 66, in ModelPredictAPI
    model_wrapper = ModelWrapper()
  File "/workspace/core/model.py", line 57, in __init__
    vocab_file='assets/vocab.txt', do_lower_case=True)
  File "/workspace/core/tokenization.py", line 151, in __init__
    self.vocab = load_vocab(vocab_file)
  File "/workspace/core/tokenization.py", line 113, in load_vocab
    token = convert_to_unicode(reader.readline())
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 183, in readline
    self._preread_check()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.PermissionDeniedError: assets/vocab.txt; Permission denied

Permissions:
```
$ ls -al
total 92
drwxr-xr-x. 1 root root   4096 Sep 13 07:24 .
drwxr-xr-x. 1 root root   4096 Sep 18 12:52 ..
-rw-r--r--. 1 root root     15 Sep 13 07:16 .dockerignore
-rw-r--r--. 1 root root   1197 Sep 13 07:16 .gitignore
-rw-r--r--. 1 root root    912 Sep 13 07:16 .travis.yml
-rw-r--r--. 1 root root   1650 Sep 13 07:16 Dockerfile
-rw-r--r--. 1 root root  11357 Sep 13 07:16 LICENSE
-rw-r--r--. 1 root root    812 May 29 00:32 README.md
drwxr-xr-x. 2 root root   4096 Sep 13 07:16 api
-rw-r--r--. 1 root root    878 Sep 13 07:16 app.py
drwxr-xr-x. 1  501 staff  4096 Sep 13 07:21 assets
-rw-r--r--. 1 root root    955 Sep 13 07:16 config.py
drwxr-xr-x. 2 root root   4096 Sep 13 07:16 core
drwxr-xr-x. 2 root root   4096 Sep 13 07:16 docs
-rw-r--r--. 1 root root   1221 Sep 13 07:16 max-question-answering.yaml
-rw-r--r--. 1 root root     23 Sep 13 07:16 requirements-test.txt
-rw-r--r--. 1 root root     45 Sep 13 07:16 requirements.txt
drwxr-xr-x. 2 root root   4096 Sep 13 07:16 samples
-rw-r--r--. 1 root root    677 Sep 13 07:16 sha512sums.txt
drwxr-xr-x. 2 root root   4096 Sep 13 07:16 tests
$ cd assets
$ ls -al
total 248
drwxr-xr-x. 1  501 staff   4096 Sep 13 07:21 .
drwxr-xr-x. 1 root root    4096 Sep 13 07:24 ..
-rwxr-xr-x. 1  501 staff    213 Sep 13 01:41 ._max_qa_model
-rw-------. 1  501 staff    350 Sep 13 01:39 ._vocab.txt
drwxr-xr-x. 3  501 staff   4096 Sep 13 07:21 max_qa_model
-rw-------. 1  501 staff 231508 Sep 13 01:39 vocab.txt
```

```

**Comment by kmh4321** [comment]
Will fix this issue and upload to `max-assets-prod` once the trainable PR is also merged incase we find some regression issues.

**Comment by kmh4321** [comment]
@ptitzler which file is the one causing issues? is it just `vocab.txt`?

**Comment by ptitzler** [comment]
Yes. The issue is that Red Hat applies strict security and uses a "random" id to run the Docker image. That id is different from the id "501" that was used when the Docker image was built. During the build `assets.tar.gz` was downloaded and extracted and the original file permissions retained. To solve the problem you need to 
- repackage `assets.tar.gz` (assuring that for all files `go+r` permissions are set) 
- upload the new version to COS
- reference the updated file in `Dockerfile`
